import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

// Load environment variables locally
dotenv.config({ path: path.join(process.cwd(), '.env.local') });

const MIGRATIONS_DIR = path.join(process.cwd(), 'libs', 'db', 'src', 'supabase', 'migrations');
const DEBUG_OUTPUT_FILE = path.join(process.cwd(), 'tools', 'scripts', 'generated-reset-debug.sql');
const TARGET_API_DIR = path.join(process.cwd(), 'apps', 'nextblock', 'app', 'api', 'cron', 'reset-sandbox');
const OUT_FILE = path.join(TARGET_API_DIR, 'sandboxResetSql.ts');

async function generateSandboxReset() {
  console.log('[generate-sandbox-reset] Starting compilation...');
  if (!fs.existsSync(MIGRATIONS_DIR)) {
    console.error(`Directory not found: ${MIGRATIONS_DIR}`);
    process.exit(1);
  }

  // 1. Read and filter migration files
  const files = fs.readdirSync(MIGRATIONS_DIR)
    .filter(f => f.endsWith('.sql'))
    .filter(f => !f.toLowerCase().includes('sandbox')) // Exclude sandbox-specific files
    .filter(f => f !== '99999999999999_auto_sandbox_reset.sql')
    .sort();

  console.log(`[generate-sandbox-reset] Found ${files.length} standard migrations.`);

  let concatenatedSql = '';
  for (const file of files) {
    console.log(` - Reading ${file}`);
    let content = fs.readFileSync(path.join(MIGRATIONS_DIR, file), 'utf-8');
    // Strip BEGIN; and COMMIT; because they cause errors inside an EXECUTE block
    content = content.replace(/(?:^|\n)\s*BEGIN\s*;/ig, '\n');
    content = content.replace(/(?:^|\n)\s*COMMIT\s*;/ig, '\n');
    concatenatedSql += `\n\n-- >>> FROM: ${file} <<<\n`;
    concatenatedSql += content;
  }

  // 2. Build the Raw Script String
  const procedureSql = `-- AUTO-GENERATED: Sandbox Reset Script. Do Not Edit Manually.
-- Generated by tools/scripts/generate-sandbox-reset.ts

  -- Step A: Erase all non-demo users
  DELETE FROM auth.users WHERE id != '63a8aa07-ef6e-4cc7-bafa-ece023c74366';

  -- Step B: Wipe public schema and truncate migrations
  DROP SCHEMA public CASCADE;
  CREATE SCHEMA public;

  -- Restore default public schema privileges so the standard migrations succeed
  GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
  GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO postgres, anon, authenticated, service_role;
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO postgres, anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;

  TRUNCATE TABLE supabase_migrations.schema_migrations;

  -- Step C: Execute full schema & seed from production migrations
${concatenatedSql}

  -- Step D: Anchor demo profile
  INSERT INTO public.profiles (id, updated_at, full_name, avatar_url, website, role)
  SELECT '63a8aa07-ef6e-4cc7-bafa-ece023c74366'::uuid, NULL, NULL, NULL, NULL, 'ADMIN'
  WHERE NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = '63a8aa07-ef6e-4cc7-bafa-ece023c74366'::uuid);
`;

  if (!fs.existsSync(TARGET_API_DIR)) {
    fs.mkdirSync(TARGET_API_DIR, { recursive: true });
  }

  // 3. Export as a typescript variable into the route directory
  const tsContent = `export const SANDBOX_RESET_SQL = \`\n${procedureSql.replace(/`/g, '\\`').replace(/\$\{/g, '\\${')}\n\`;\n`;
  fs.writeFileSync(OUT_FILE, tsContent);
  
  // Also save a fallback copy locally for debugging
  fs.writeFileSync(DEBUG_OUTPUT_FILE, procedureSql);
  
  console.log(`[generate-sandbox-reset] ✅ Successfully compiled Sandbox Reset SQL to ${OUT_FILE}`);
}

generateSandboxReset();
