import * as fs from 'fs';
import * as path from 'path';
// eslint-disable-next-line @nx/enforce-module-boundaries
import postgres from 'postgres';
import * as dotenv from 'dotenv';

// Load environment variables locally
dotenv.config({ path: path.join(process.cwd(), '.env.local') });

const MIGRATIONS_DIR = path.join(process.cwd(), 'libs', 'db', 'src', 'supabase', 'migrations');
const DEBUG_OUTPUT_FILE = path.join(process.cwd(), 'tools', 'scripts', 'generated-reset-debug.sql');

async function generateSandboxReset() {
  console.log('[generate-sandbox-reset] Starting compilation...');
  if (!fs.existsSync(MIGRATIONS_DIR)) {
    console.error(`Directory not found: ${MIGRATIONS_DIR}`);
    process.exit(1);
  }

  const databaseUrl = process.env.POSTGRES_URL || process.env.DATABASE_URL;
  if (!databaseUrl) {
    console.error('[generate-sandbox-reset] ERROR: POSTGRES_URL is not set in environment.');
    process.exit(1);
  }

  // 1. Read and filter migration files
  const files = fs.readdirSync(MIGRATIONS_DIR)
    .filter(f => f.endsWith('.sql'))
    .filter(f => !f.toLowerCase().includes('sandbox')) // Exclude sandbox-specific files
    .filter(f => f !== '99999999999999_auto_sandbox_reset.sql')
    .sort();

  console.log(`[generate-sandbox-reset] Found ${files.length} standard migrations.`);

  let concatenatedSql = '';
  for (const file of files) {
    console.log(` - Reading ${file}`);
    let content = fs.readFileSync(path.join(MIGRATIONS_DIR, file), 'utf-8');
    // Strip BEGIN; and COMMIT; because they cause errors inside an EXECUTE block
    content = content.replace(/(?:^|\n)\s*BEGIN\s*;/ig, '\n');
    content = content.replace(/(?:^|\n)\s*COMMIT\s*;/ig, '\n');
    concatenatedSql += `\n\n-- >>> FROM: ${file} <<<\n`;
    concatenatedSql += content;
  }

  // Use a unique dollar quote delimiter so inner functions/migrated syntax doesn't break
  const delimiter = `$nextblock_sandbox_reset$`;

  // 2. Build the RPC string
  const procedureSql = `-- AUTO-GENERATED: Sandbox Reset Function. Do Not Edit Manually.
-- Generated by tools/scripts/generate-sandbox-reset.ts

CREATE OR REPLACE FUNCTION public.reset_sandbox_state()
RETURNS void AS $reset_sandbox_state$
BEGIN
  -- Step A: Erase all non-demo users
  DELETE FROM auth.users WHERE id != '63a8aa07-ef6e-4cc7-bafa-ece023c74366';

  -- Step B: Wipe public schema and truncate migrations
  DROP SCHEMA public CASCADE;
  CREATE SCHEMA public;

  -- Restore default public schema privileges so the standard migrations succeed
  GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
  GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO postgres, anon, authenticated, service_role;
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO postgres, anon, authenticated, service_role;
  ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;

  TRUNCATE TABLE supabase_migrations.schema_migrations;

  -- Step C: Execute full schema & seed from production migrations
  EXECUTE ${delimiter}
${concatenatedSql}
  ${delimiter};

  -- Step D: Anchor demo profile
  INSERT INTO public.profiles (id, updated_at, full_name, avatar_url, website, role)
  SELECT '63a8aa07-ef6e-4cc7-bafa-ece023c74366'::uuid, NULL, NULL, NULL, NULL, 'ADMIN'
  WHERE NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = '63a8aa07-ef6e-4cc7-bafa-ece023c74366'::uuid);

END;
$reset_sandbox_state$ LANGUAGE plpgsql SECURITY DEFINER;
`;

  // 3. Save the wrapper locally for debugging purposes ONLY (not to migrations)
  fs.writeFileSync(DEBUG_OUTPUT_FILE, procedureSql);
  console.log(`\n[generate-sandbox-reset] Saved debug SQL to ${DEBUG_OUTPUT_FILE}`);

  // 4. Execute the SQL against the remote Supabase database directly
  console.log(`[generate-sandbox-reset] Connecting to database via DATABASE_URL...`);
  
  // Use postgres.js to connect to postgres. Ensure SSL is required for Supabase
  const sql = postgres(databaseUrl, { ssl: 'require' });

  try {
    await sql.unsafe(procedureSql);
    console.log(`[generate-sandbox-reset] ✅ Successfully injected reset_sandbox_state() into the Sandbox DB!`);
  } catch (error) {
    console.error(`[generate-sandbox-reset] ❌ Failed to inject function:`, error);
    process.exit(1);
  } finally {
    await sql.end();
  }
}

generateSandboxReset();
