import { SupabaseClient } from '@supabase/supabase-js';
import { Database } from '@nextblock-cms/db';
import { ProductFormValues } from './product-schema';
export declare function getProducts(supabase: SupabaseClient<Database>, { page, limit, search }?: {
    page?: number;
    limit?: number;
    search?: string;
}): Promise<import("@supabase/postgrest-js").PostgrestSingleResponse<(import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'blocks'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'languages'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'pages'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'posts'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'logos'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'media'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'profiles'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'navigation_items'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'page_revisions'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'post_revisions'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'site_settings'."> | import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"column 'id' does not exist on 'translations'.">)[]>>;
export declare function getProduct(supabase: SupabaseClient<Database>, id: string): Promise<import("@supabase/postgrest-js").PostgrestSingleResponse<{
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between blocks and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between languages and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between pages and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between posts and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between logos and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between media and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between profiles and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between navigation_items and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between page_revisions and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between post_revisions and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between site_settings and product_media">;
} | {
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
    product_media: import("node_modules/@supabase/postgrest-js/dist/cjs/select-query-parser/utils").SelectQueryError<"could not find the relation between translations and product_media">;
}>>;
export declare function createProduct(supabase: SupabaseClient<Database>, data: ProductFormValues): Promise<{
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
}>;
export declare function updateProduct(supabase: SupabaseClient<Database>, id: string, data: ProductFormValues): Promise<{
    block_type: string;
    content: import("@nextblock-cms/db").Json | null;
    created_at: string;
    id: number;
    language_id: number;
    order: number;
    page_id: number | null;
    post_id: number | null;
    updated_at: string;
} | {
    code: string;
    created_at: string;
    id: number;
    is_active: boolean;
    is_default: boolean;
    name: string;
    updated_at: string;
} | {
    created_at: string;
    id: string;
    media_id: string | null;
    name: string;
} | {
    blur_data_url: string | null;
    created_at: string;
    description: string | null;
    file_name: string;
    file_path: string | null;
    file_type: string | null;
    folder: string | null;
    height: number | null;
    id: string;
    object_key: string;
    size_bytes: number | null;
    updated_at: string;
    uploader_id: string | null;
    variants: import("@nextblock-cms/db").Json | null;
    width: number | null;
} | {
    created_at: string;
    id: number;
    label: string;
    language_id: number;
    menu_key: Database["public"]["Enums"]["menu_location"];
    order: number;
    page_id: number | null;
    parent_id: number | null;
    translation_group_id: string;
    updated_at: string;
    url: string;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    page_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
} | {
    author_id: string | null;
    created_at: string;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
} | {
    author_id: string | null;
    content: import("@nextblock-cms/db").Json;
    created_at: string;
    id: number;
    post_id: number;
    revision_type: Database["public"]["Enums"]["revision_type"];
    version: number;
} | {
    author_id: string | null;
    created_at: string;
    excerpt: string | null;
    feature_image_id: string | null;
    id: number;
    language_id: number;
    meta_description: string | null;
    meta_title: string | null;
    published_at: string | null;
    slug: string;
    status: Database["public"]["Enums"]["page_status"];
    title: string;
    translation_group_id: string;
    updated_at: string;
    version: number;
} | {
    avatar_url: string | null;
    full_name: string | null;
    id: string;
    role: Database["public"]["Enums"]["user_role"];
    updated_at: string | null;
    username: string | null;
    website: string | null;
} | {
    key: string;
    value: import("@nextblock-cms/db").Json | null;
} | {
    created_at: string;
    key: string;
    translations: import("@nextblock-cms/db").Json;
    updated_at: string;
}>;
