-- 00000000000006_setup_pages.sql
-- Setup pages table

CREATE TABLE public.pages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  language_id bigint NOT NULL REFERENCES public.languages(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  slug text NOT NULL,
  status public.page_status NOT NULL DEFAULT 'draft',
  meta_title text,
  meta_description text,

  -- Added columns
  version integer NOT NULL DEFAULT 1,
  translation_group_id uuid DEFAULT gen_random_uuid() NOT NULL,

  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.pages IS 'Stores static pages for the website.';
COMMENT ON COLUMN public.pages.slug IS 'URL-friendly identifier, unique per language.';
COMMENT ON COLUMN public.pages.version IS 'Monotonic version number for hybrid revisions.';
COMMENT ON COLUMN public.pages.translation_group_id IS 'Groups different language versions of the same conceptual page.';

-- Constraints
ALTER TABLE public.pages
  ADD CONSTRAINT pages_language_id_slug_key UNIQUE (language_id, slug);

-- Indexes
CREATE INDEX idx_pages_author_id ON public.pages(author_id);
CREATE INDEX idx_pages_translation_group_id ON public.pages(translation_group_id);

-- Trigger: handle_pages_update
CREATE OR REPLACE FUNCTION public.handle_pages_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_pages_update
  BEFORE UPDATE ON public.pages
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_pages_update();
