-- 00000000000005_setup_posts.sql
-- Setup posts table

CREATE TABLE public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  language_id bigint NOT NULL REFERENCES public.languages(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  slug text NOT NULL,
  excerpt text,
  status public.page_status NOT NULL DEFAULT 'draft',
  published_at timestamp with time zone,
  meta_title text,
  meta_description text,
  
  -- Added columns
  feature_image_id uuid REFERENCES public.media(id) ON DELETE SET NULL,
  version integer NOT NULL DEFAULT 1,
  translation_group_id uuid DEFAULT gen_random_uuid() NOT NULL,

  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.posts IS 'Stores blog posts or news articles.';
COMMENT ON COLUMN public.posts.slug IS 'URL-friendly identifier, unique per language.';
COMMENT ON COLUMN public.posts.feature_image_id IS 'ID of the media item to be used as the feature image.';
COMMENT ON COLUMN public.posts.version IS 'Monotonic version number for hybrid revisions.';
COMMENT ON COLUMN public.posts.translation_group_id IS 'Groups different language versions of the same conceptual post.';

-- Constraints
ALTER TABLE public.posts
  ADD CONSTRAINT posts_language_id_slug_key UNIQUE (language_id, slug);

-- Indexes
CREATE INDEX idx_posts_feature_image_id ON public.posts(feature_image_id);
CREATE INDEX idx_posts_author_id ON public.posts(author_id);
CREATE INDEX idx_posts_translation_group_id ON public.posts(translation_group_id);

-- Trigger: handle_posts_update
CREATE OR REPLACE FUNCTION public.handle_posts_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_posts_update
  BEFORE UPDATE ON public.posts
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_posts_update();
