-- 00000000000001_setup_cms_core.sql
-- Consolidated migration preserving original statement order within grouped sections.

-- 00000000000003_setup_site_settings_and_profiles.sql
-- Global settings, user profiles, and saved addresses.

CREATE TABLE public.site_settings (
  key text PRIMARY KEY,
  value jsonb
);

COMMENT ON TABLE public.site_settings IS 'Key-value store for global site settings.';

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at timestamptz,
  full_name text,
  avatar_url text,
  website text,
  github_username text,
  phone text,
  role public.user_role NOT NULL DEFAULT 'USER'
);

COMMENT ON TABLE public.profiles IS 'Profile information for each user, extending auth.users.';
COMMENT ON COLUMN public.profiles.id IS 'References auth.users.id';
COMMENT ON COLUMN public.profiles.role IS 'User role for RBAC.';

CREATE TABLE public.user_addresses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  address_type text NOT NULL CHECK (address_type IN ('billing', 'shipping')),
  is_default boolean NOT NULL DEFAULT false,
  recipient_name text,
  company_name text,
  line1 text,
  line2 text,
  city text,
  state text,
  postal_code text,
  country_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN public.user_addresses.company_name IS
  'Optional company or organization name for the address.';

CREATE UNIQUE INDEX idx_user_addresses_one_default_per_type
  ON public.user_addresses (user_id, address_type)
  WHERE is_default = true;

-- 00000000000004_setup_languages_and_media.sql
-- Core locale and media tables.

CREATE TABLE public.languages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  is_default boolean NOT NULL DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.languages IS 'Stores supported languages for the CMS.';
COMMENT ON COLUMN public.languages.code IS 'BCP 47 language code.';

CREATE UNIQUE INDEX ensure_single_default_language_idx
  ON public.languages (is_default)
  WHERE is_default = true;

CREATE TABLE public.media (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  uploader_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  file_name text NOT NULL,
  object_key text NOT NULL UNIQUE,
  file_type text,
  size_bytes bigint,
  description text,
  width integer,
  height integer,
  blur_data_url text,
  variants jsonb,
  file_path text,
  folder text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.media IS 'Stores information about uploaded media assets.';
COMMENT ON COLUMN public.media.object_key IS 'Unique key (path) in Cloudflare R2.';
COMMENT ON COLUMN public.media.width IS 'Width of the image in pixels.';
COMMENT ON COLUMN public.media.height IS 'Height of the image in pixels.';
COMMENT ON COLUMN public.media.blur_data_url IS 'Base64 encoded string for image blur placeholders.';
COMMENT ON COLUMN public.media.variants IS 'Array of image variant objects.';
COMMENT ON COLUMN public.media.file_path IS 'Full path to the file in the storage bucket.';
COMMENT ON COLUMN public.media.folder IS 'Folder path prefix for the R2 object.';

-- 00000000000005_setup_translations_and_branding.sql
-- Shared translation storage and logo metadata.

CREATE TABLE public.translations (
  key text PRIMARY KEY,
  translations jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON COLUMN public.translations.key IS
  'A unique, slugified identifier (e.g., "sign_in_button_text").';
COMMENT ON COLUMN public.translations.translations IS
  'Stores translations as key-value pairs (e.g., {"en": "Sign In", "fr": "S''inscrire"}).';

CREATE TABLE public.logos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  media_id uuid REFERENCES public.media(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.logos IS 'Stores company and brand logos.';
COMMENT ON COLUMN public.logos.name IS 'The name of the brand or company for the logo.';
COMMENT ON COLUMN public.logos.media_id IS 'Foreign key to the media table for the logo image.';
