-- 00000000000015_setup_product_drafts.sql
-- Product draft snapshots for front-end visual editing.

CREATE TABLE public.product_drafts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT product_drafts_product_unique UNIQUE (product_id),
  CONSTRAINT product_drafts_meta_object CHECK (jsonb_typeof(meta) = 'object')
);

COMMENT ON TABLE public.product_drafts IS
  'Draft product metadata snapshots used by Draft Mode and front-end visual editing before publishing to live product rows.';
COMMENT ON COLUMN public.product_drafts.product_id IS
  'ID of the product being drafted.';
COMMENT ON COLUMN public.product_drafts.meta IS
  'Draft product metadata snapshot. Front-end visual editing currently mutates visible title, short_description, and description_json fields.';

CREATE INDEX product_drafts_author_id_idx ON public.product_drafts (author_id);
CREATE INDEX product_drafts_product_id_idx ON public.product_drafts (product_id);
CREATE INDEX product_drafts_updated_at_idx ON public.product_drafts (updated_at DESC);

DROP TRIGGER IF EXISTS on_product_drafts_update ON public.product_drafts;
CREATE TRIGGER on_product_drafts_update
  BEFORE UPDATE ON public.product_drafts
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();

ALTER TABLE public.product_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY product_drafts_select_policy
  ON public.product_drafts
  FOR SELECT
  TO authenticated
  USING ((SELECT public.get_current_user_role()) IN ('ADMIN', 'WRITER'));

CREATE POLICY product_drafts_insert_policy
  ON public.product_drafts
  FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT public.get_current_user_role()) IN ('ADMIN', 'WRITER'));

CREATE POLICY product_drafts_update_policy
  ON public.product_drafts
  FOR UPDATE
  TO authenticated
  USING ((SELECT public.get_current_user_role()) IN ('ADMIN', 'WRITER'))
  WITH CHECK ((SELECT public.get_current_user_role()) IN ('ADMIN', 'WRITER'));

CREATE POLICY product_drafts_delete_policy
  ON public.product_drafts
  FOR DELETE
  TO authenticated
  USING ((SELECT public.get_current_user_role()) IN ('ADMIN', 'WRITER'));
