-- 00000000000014_setup_content_drafts.sql
-- Draft snapshots for front-end visual editing.

CREATE TABLE IF NOT EXISTS public.content_drafts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_type text NOT NULL CHECK (parent_type IN ('page', 'post')),
  parent_id bigint NOT NULL,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  base_version integer NOT NULL DEFAULT 1,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  blocks jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT content_drafts_parent_unique UNIQUE (parent_type, parent_id),
  CONSTRAINT content_drafts_blocks_array CHECK (jsonb_typeof(blocks) = 'array'),
  CONSTRAINT content_drafts_meta_object CHECK (jsonb_typeof(meta) = 'object')
);

ALTER TABLE public.content_drafts
  ADD COLUMN IF NOT EXISTS parent_type text,
  ADD COLUMN IF NOT EXISTS parent_id bigint,
  ADD COLUMN IF NOT EXISTS author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS base_version integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS blocks jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'content_drafts_parent_unique'
      AND conrelid = 'public.content_drafts'::regclass
  ) THEN
    ALTER TABLE public.content_drafts
      ADD CONSTRAINT content_drafts_parent_unique UNIQUE (parent_type, parent_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'content_drafts_blocks_array'
      AND conrelid = 'public.content_drafts'::regclass
  ) THEN
    ALTER TABLE public.content_drafts
      ADD CONSTRAINT content_drafts_blocks_array CHECK (jsonb_typeof(blocks) = 'array');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'content_drafts_meta_object'
      AND conrelid = 'public.content_drafts'::regclass
  ) THEN
    ALTER TABLE public.content_drafts
      ADD CONSTRAINT content_drafts_meta_object CHECK (jsonb_typeof(meta) = 'object');
  END IF;
END $$;

COMMENT ON TABLE public.content_drafts IS
  'Draft snapshots used by Draft Mode and front-end visual editing before publishing to live page/post rows.';
COMMENT ON COLUMN public.content_drafts.parent_type IS
  'The content table this draft belongs to: page or post.';
COMMENT ON COLUMN public.content_drafts.parent_id IS
  'ID of the page or post being drafted.';
COMMENT ON COLUMN public.content_drafts.base_version IS
  'Published page/post version the draft was created from.';
COMMENT ON COLUMN public.content_drafts.meta IS
  'Draft page/post metadata snapshot.';
COMMENT ON COLUMN public.content_drafts.blocks IS
  'Ordered draft block snapshot, including block ids, block types, content, language ids, and order values.';

CREATE INDEX IF NOT EXISTS content_drafts_author_id_idx ON public.content_drafts (author_id);
CREATE INDEX IF NOT EXISTS content_drafts_parent_idx ON public.content_drafts (parent_type, parent_id);
CREATE INDEX IF NOT EXISTS content_drafts_updated_at_idx ON public.content_drafts (updated_at DESC);

DROP TRIGGER IF EXISTS on_content_drafts_update ON public.content_drafts;
CREATE TRIGGER on_content_drafts_update
  BEFORE UPDATE ON public.content_drafts
  FOR EACH ROW
  EXECUTE FUNCTION public.set_current_timestamp_updated_at();

ALTER TABLE public.content_drafts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS content_drafts_select_policy
  ON public.content_drafts;

CREATE POLICY content_drafts_select_policy
  ON public.content_drafts
  FOR SELECT
  TO authenticated
  USING ((SELECT public.get_current_user_role()) IN ('ADMIN', 'WRITER'));

DROP POLICY IF EXISTS content_drafts_insert_policy
  ON public.content_drafts;

CREATE POLICY content_drafts_insert_policy
  ON public.content_drafts
  FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT public.get_current_user_role()) IN ('ADMIN', 'WRITER'));

DROP POLICY IF EXISTS content_drafts_update_policy
  ON public.content_drafts;

CREATE POLICY content_drafts_update_policy
  ON public.content_drafts
  FOR UPDATE
  TO authenticated
  USING ((SELECT public.get_current_user_role()) IN ('ADMIN', 'WRITER'))
  WITH CHECK ((SELECT public.get_current_user_role()) IN ('ADMIN', 'WRITER'));

DROP POLICY IF EXISTS content_drafts_delete_policy
  ON public.content_drafts;

CREATE POLICY content_drafts_delete_policy
  ON public.content_drafts
  FOR DELETE
  TO authenticated
  USING ((SELECT public.get_current_user_role()) IN ('ADMIN', 'WRITER'));
