-- 00000000000003_setup_languages.sql
-- Setup languages table

-- 1. Create languages table
CREATE TABLE public.languages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE, -- e.g., 'en', 'fr'
  name text NOT NULL, -- e.g., 'English', 'Français'
  is_default boolean NOT NULL DEFAULT false,
  is_active boolean DEFAULT true, -- Added from later migration
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.languages IS 'Stores supported languages for the CMS.';
COMMENT ON COLUMN public.languages.code IS 'BCP 47 language code.';

-- 2. Indexes
CREATE UNIQUE INDEX ensure_single_default_language_idx
ON public.languages (is_default)
WHERE (is_default = true);

-- 3. Seed initial languages
INSERT INTO public.languages (code, name, is_default, is_active)
VALUES
  ('en', 'English', true, true),
  ('fr', 'Français', false, true);

-- 4. Trigger: handle_languages_update
CREATE OR REPLACE FUNCTION public.handle_languages_update()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_languages_update
  BEFORE UPDATE ON public.languages
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_languages_update();
