-- 00000000000002_setup_content_tables.sql
-- Consolidated migration preserving original statement order within grouped sections.

-- 00000000000006_setup_pages_and_posts.sql
-- Page and post records.

CREATE TABLE public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  language_id bigint NOT NULL REFERENCES public.languages(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  slug text NOT NULL,
  label text,
  excerpt text,
  subtitle text,
  status public.page_status NOT NULL DEFAULT 'draft',
  published_at timestamptz,
  meta_title text,
  meta_description text,
  feature_image_id uuid REFERENCES public.media(id) ON DELETE SET NULL,
  version integer NOT NULL DEFAULT 1,
  translation_group_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT posts_language_id_slug_key UNIQUE (language_id, slug)
);

COMMENT ON TABLE public.posts IS 'Stores blog posts or news articles.';
COMMENT ON COLUMN public.posts.slug IS 'URL-friendly identifier, unique per language.';
COMMENT ON COLUMN public.posts.label IS
  'Short editorial label rendered as a pill on post hero and article cards.';
COMMENT ON COLUMN public.posts.excerpt IS
  'Short editorial summary used in post metadata rows and post cards.';
COMMENT ON COLUMN public.posts.subtitle IS
  'Longer deck shown under the post title.';
COMMENT ON COLUMN public.posts.feature_image_id IS
  'ID of the media item to be used as the feature image.';
COMMENT ON COLUMN public.posts.version IS 'Monotonic version number for hybrid revisions.';
COMMENT ON COLUMN public.posts.translation_group_id IS
  'Groups different language versions of the same conceptual post.';

CREATE TABLE public.pages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  language_id bigint NOT NULL REFERENCES public.languages(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  slug text NOT NULL,
  status public.page_status NOT NULL DEFAULT 'draft',
  meta_title text,
  meta_description text,
  version integer NOT NULL DEFAULT 1,
  translation_group_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pages_language_id_slug_key UNIQUE (language_id, slug)
);

COMMENT ON TABLE public.pages IS 'Stores static pages for the website.';
COMMENT ON COLUMN public.pages.slug IS 'URL-friendly identifier, unique per language.';
COMMENT ON COLUMN public.pages.version IS 'Monotonic version number for hybrid revisions.';
COMMENT ON COLUMN public.pages.translation_group_id IS
  'Groups different language versions of the same conceptual page.';

-- 00000000000007_setup_blocks_and_navigation.sql
-- Content blocks and navigation trees.

CREATE TABLE public.blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id bigint REFERENCES public.pages(id) ON DELETE CASCADE,
  post_id bigint REFERENCES public.posts(id) ON DELETE CASCADE,
  language_id bigint NOT NULL REFERENCES public.languages(id) ON DELETE CASCADE,
  block_type text NOT NULL,
  content jsonb,
  "order" integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT check_exactly_one_parent CHECK (
    (page_id IS NOT NULL AND post_id IS NULL)
    OR (post_id IS NOT NULL AND page_id IS NULL)
  )
);

COMMENT ON TABLE public.blocks IS 'Stores content blocks for pages and posts.';
COMMENT ON COLUMN public.blocks.block_type IS
  'Type of the block, e.g., "text", "image".';
COMMENT ON COLUMN public.blocks.content IS 'JSONB content specific to the block_type.';
COMMENT ON COLUMN public.blocks.order IS 'Sort order of the block.';

CREATE TABLE public.navigation_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  language_id bigint NOT NULL REFERENCES public.languages(id) ON DELETE CASCADE,
  menu_key public.menu_location NOT NULL,
  label text NOT NULL,
  url text NOT NULL,
  parent_id bigint REFERENCES public.navigation_items(id) ON DELETE CASCADE,
  "order" integer NOT NULL DEFAULT 0,
  page_id bigint REFERENCES public.pages(id) ON DELETE SET NULL,
  translation_group_id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.navigation_items IS 'Stores navigation menu items.';
COMMENT ON COLUMN public.navigation_items.menu_key IS
  'Identifies the menu this item belongs to.';

-- 00000000000008_setup_revisions.sql
-- Page and post revision history.

CREATE TABLE public.page_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id bigint NOT NULL REFERENCES public.pages(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  version integer NOT NULL,
  revision_type public.revision_type NOT NULL,
  content jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT page_revisions_page_version_key UNIQUE (page_id, version)
);

COMMENT ON TABLE public.page_revisions IS 'Hybrid (snapshot/diff) revisions for pages.';
COMMENT ON COLUMN public.page_revisions.content IS
  'If snapshot: full content; if diff: JSON Patch array.';

CREATE TABLE public.post_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  version integer NOT NULL,
  revision_type public.revision_type NOT NULL,
  content jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT post_revisions_post_version_key UNIQUE (post_id, version)
);

COMMENT ON TABLE public.post_revisions IS 'Hybrid (snapshot/diff) revisions for posts.';
COMMENT ON COLUMN public.post_revisions.content IS
  'If snapshot: full content; if diff: JSON Patch array.';
