-- 00000000000008_setup_navigation.sql
-- Setup navigation_items table

CREATE TABLE public.navigation_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  language_id bigint NOT NULL REFERENCES public.languages(id) ON DELETE CASCADE,
  menu_key public.menu_location NOT NULL,
  label text NOT NULL,
  url text NOT NULL,
  parent_id bigint REFERENCES public.navigation_items(id) ON DELETE CASCADE,
  "order" integer NOT NULL DEFAULT 0,
  page_id bigint REFERENCES public.pages(id) ON DELETE SET NULL,
  
  -- Added columns (if any, checking previous files... none explicitly added but translation_group_id was mentioned in index drop?)
  -- 20250520171900_add_translation_group_to_nav_items.sql was listed.
  -- Let's assume we want it if it was there. I'll double check the file list.
  -- Yes: 20250520171900_add_translation_group_to_nav_items.sql
  -- I should add it.
  translation_group_id uuid DEFAULT gen_random_uuid() NOT NULL,

  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.navigation_items IS 'Stores navigation menu items.';
COMMENT ON COLUMN public.navigation_items.menu_key IS 'Identifies the menu this item belongs to.';

-- Indexes
CREATE INDEX idx_navigation_items_menu_lang_order ON public.navigation_items (menu_key, language_id, "order");
CREATE INDEX idx_navigation_items_language_id ON public.navigation_items(language_id);
CREATE INDEX idx_navigation_items_page_id ON public.navigation_items(page_id);
CREATE INDEX idx_navigation_items_parent_id ON public.navigation_items(parent_id);
-- Note: idx_navigation_items_translation_group_id was dropped in optimize_indexes.sql as unused, so I won't create it.

-- Trigger: handle_navigation_items_update
CREATE OR REPLACE FUNCTION public.handle_navigation_items_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_navigation_items_update
  BEFORE UPDATE ON public.navigation_items
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_navigation_items_update();
