-- 00000000000011_setup_revisions.sql
-- Setup revisions tables

-- 1. Page Revisions
CREATE TABLE public.page_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id bigint NOT NULL REFERENCES public.pages(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  version integer NOT NULL,
  revision_type public.revision_type NOT NULL,
  content jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT page_revisions_page_version_key UNIQUE (page_id, version)
);

COMMENT ON TABLE public.page_revisions IS 'Hybrid (snapshot/diff) revisions for pages.';
COMMENT ON COLUMN public.page_revisions.content IS 'If snapshot: full content; if diff: JSON Patch array.';

CREATE INDEX idx_page_revisions_page_id ON public.page_revisions(page_id);
CREATE INDEX idx_page_revisions_page_id_version ON public.page_revisions(page_id, version);

-- 2. Post Revisions
CREATE TABLE public.post_revisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  version integer NOT NULL,
  revision_type public.revision_type NOT NULL,
  content jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT post_revisions_post_version_key UNIQUE (post_id, version)
);

COMMENT ON TABLE public.post_revisions IS 'Hybrid (snapshot/diff) revisions for posts.';
COMMENT ON COLUMN public.post_revisions.content IS 'If snapshot: full content; if diff: JSON Patch array.';

CREATE INDEX idx_post_revisions_post_id ON public.post_revisions(post_id);
CREATE INDEX idx_post_revisions_post_id_version ON public.post_revisions(post_id, version);
